// pub fn render(is_maximized: bool) -> impl IntoElement {
//     div().flex().flex_col().size_full().child(
//         div()
//             .flex()
//             .h(px(32.))
//             .px_1()
//             .bg(gpui::black())
//             .text_color(gpui::white())
//             .w_full()
//             .items_center()
//             .child(div().child("DTBox"))
//             .child(
//                 div()
//                     .bg(gpui::blue())
//                     .h(px(32.))
//                     .w_full()
//                     .window_control_area(gpui::WindowControlArea::Drag),
//             )
//             .child(
//                 div()
//                     .flex()
//                     .flex_row()
//                     .gap_2()
//                     .child(
//                         div()
//                             .flex_none()
//                             .px_2()
//                             .border_1()
//                             .border_color(rgb(0xe0e0e0))
//                             .rounded_sm()
//                             .cursor_pointer()
//                             .child("-")
//                             .window_control_area(gpui::WindowControlArea::Min),
//                     )
//                     .child(
//                         div()
//                             .flex_none()
//                             .px_2()
//                             .border_1()
//                             .border_color(rgb(0xe0e0e0))
//                             .rounded_sm()
//                             .cursor_pointer()
//                             .child(if is_maximized { "🗗" } else { "□" })
//                             .window_control_area(gpui::WindowControlArea::Max),
//                     )
//                     .child(
//                         div()
//                             .flex_none()
//                             .px_2()
//                             .border_1()
//                             .border_color(rgb(0xe0e0e0))
//                             .rounded_sm()
//                             .cursor_pointer()
//                             .child("✕")
//                             .window_control_area(gpui::WindowControlArea::Close),
//                     ),
//             ),
//     )
// }
