import { DTBWindow } from "window.slint";
import { Button } from "std-widgets.slint";

export component MainWindow inherits DTBWindow {
    title: "DTBox";
    width: 400px;
    height: 300px;
    VerticalLayout {
        HorizontalLayout {
            height: 10%;
            Button {
                text: "hello";
            }

            Button {
                text: "hello";
            }

            Button {
                text: "hello";
            }
        }

        Rectangle { }
    }
}
