import { Button } from "std-widgets.slint";
export component WindowTitleBar inherits HorizontalLayout {
    Text {
        font-size: 20px;
        text: "00:00:00";
    }

    Rectangle { }

    Button {
        icon: @image-url("./resources/Fixed.svg");
    }

    Button {
        icon: @image-url("./resources/Reduce.svg");
    }

    Button {
        icon: @image-url("./resources/Fullscreen.svg");
    }

    Button {
        icon: @image-url("./resources/Close.svg");
    }
}

export component DTBWindow inherits Window {
    VerticalLayout {
        WindowTitleBar {
            height: 30px;
        }

        Rectangle {
            @children
        }
    }
}
